### Get all persons
GET http://localhost:3001/api/persons

### Get one person
GET http://localhost:3001/api/persons/2

### Delete one person
DELETE http://localhost:3001/api/persons/2

### Add a person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Linus Torvalds",
  "number": "123-456789"
}