### Get all persons
GET https://phone-book-7wog.onrender.com/
### Get one person
GET https://phone-book-7wog.onrender.com/
### Delete one person
DELETE https://phone-book-7wog.onrender.com/

### Add a person
POST https://phone-book-7wog.onrender.com/
Content-Type: application/json

{
  "name": "Linus Torvalds",
  "number": "123-456789"
}